"""Add chatbot owner

Revision ID: bf42c17af2e3
Revises: bf2a5d9f6f36
Create Date: 2026-06-30 10:28:10.643896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf42c17af2e3'
down_revision: Union[str, Sequence[str], None] = 'bf2a5d9f6f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chatbots', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbots', type_='foreignkey')
    op.drop_column('chatbots', 'owner_id')
    # ### end Alembic commands ###
